channels:
- conda-forge
dependencies:
- python=3.8.17
- pip<=23.2.1
- pip:
  - mlflow==2.8.1
  - cloudpickle==2.2.1
  - numpy==1.23.5
  - packaging==23.0
  - psutil==5.9.5
  - pyyaml==6.0.1
  - scikit-learn==1.3.2
  - scipy==1.10.1
name: mlflow-env
